version: '3.8'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "$UID:$GID"
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=false
    networks:
      - app

  loki:
    container_name: loki
    image: grafana/loki:latest
    restart: unless-stopped
    ports:
      - 3100:3100
    #    volumes:
    #      - ./loki-config/local-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app

  promtail:
    container_name: promtail
    image:  grafana/promtail:latest
    restart: unless-stopped
    volumes:
      - ./promtail-config/promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - app

  prometheus:
    container_name: prometheus
    image: bitnami/prometheus:latest
    stdin_open: true
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml

  node_exporter:
    container_name: node_exporter
    image: bitnami/node-exporter:latest
    restart: unless-stopped
    ports:
      - 9100:9100

networks:
  app:
    name: app

volumes:
  grafana-data: {}