apiVersion: apps/v1
kind: Deployment
metadata:
  name: apk-nginx
spec:
  revisionHistoryLimit: 5
  replicas: 3
  selector:
    matchLabels:
      app: apk-nginx
  template:
    metadata:
      labels:
        app: apk-nginx
    spec:
      containers:
        - name: apk-nginx
          image: nginx:1.22.1
          resources:
            limits:
              memory: "100Mi"
              cpu:  "10m"
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DATABASE_USERNAME
                  name: config-apk-yaml
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DATABASE_PASSWORD
                  name: config-apk
---
apiVersion: v1
kind: Secret
metadata:
  name: config-apk-yaml
data:
  DATABASE_USERNAME: cmVpeWFyZWl5YQ==